services:
  app:
    image: alexandersus/home-collection-app:v1
    container_name: app
    build: .
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    env_file: 
      - .env
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pgdata:
