services:
  app:
    image: alexandersus/home-collection-app:v1
    container_name: app
    build: .
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    env_file: 
    - .env
    networks:
      - server-net
    restart: unless-stopped
  db:
    image: alexandersus/home-collection-db:v1
    container_name: postgres
    build: ./db
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - server-net
volumes:
  pgdata:
networks:
  server-net:
    driver: bridge